// <auto-generated />
using System;
using Highscores.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Highscores.Infrastructure.Migrations
{
    [DbContext(typeof(HighscoresDbContext))]
    [Migration("20230918143843_Highscores")]
    partial class Highscores
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Highscores.Domain.Entities.Highscore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Id");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("Player");

                    b.Property<int>("Score")
                        .HasColumnType("INT")
                        .HasColumnName("Score");

                    b.HasKey("Id")
                        .HasName("PK_Highscores_Id");

                    b.HasIndex(new[] { "Id" }, "IX_Highscores_Id")
                        .IsUnique();

                    b.ToTable("Highscores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
